theme: jekyll-theme-hacker
show_downloads: "true"
title: "Space Soup Stellar Crawler"
description: "Space Soup Stellar Crawler game hosting"
release_url: "https://github.com/ssscgame/sssc-ghpages/releases/download/0.3.1"
repository: "ssscgame/sssc-ghpages"